//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaiSanCoDinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHACUNGCAP
    {
        public NHACUNGCAP()
        {
            this.PHIEUNHAP = new HashSet<PHIEUNHAP>();
        }
    
        public int manhacungcap { get; set; }
        public string tennhacungcap { get; set; }
        public string diachi { get; set; }
        public string sdt { get; set; }
    
        public virtual ICollection<PHIEUNHAP> PHIEUNHAP { get; set; }
    }
}
