//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaiSanCoDinh.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TSCDEntities2 : DbContext
    {
        public TSCDEntities2()
            : base("name=TSCDEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIETPHIEUGIAO> CHITIETPHIEUGIAO { get; set; }
        public virtual DbSet<DONVI> DONVI { get; set; }
        public virtual DbSet<DONVITINH> DONVITINH { get; set; }
        public virtual DbSet<LOAITHIETBI> LOAITHIETBI { get; set; }
        public virtual DbSet<NHACUNGCAP> NHACUNGCAP { get; set; }
        public virtual DbSet<PHIEUGIAO> PHIEUGIAO { get; set; }
        public virtual DbSet<PHIEUNHAP> PHIEUNHAP { get; set; }
        public virtual DbSet<PHONGQUANTRI> PHONGQUANTRI { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TINHTRANG> TINHTRANG { get; set; }
        public virtual DbSet<THIETBI> THIETBI { get; set; }
    }
}
