//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaiSanCoDinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINHTRANG
    {
        public TINHTRANG()
        {
            this.THIETBI = new HashSet<THIETBI>();
        }
    
        public int matinhtrang { get; set; }
        public string tentinhtrang { get; set; }
    
        public virtual ICollection<THIETBI> THIETBI { get; set; }
    }
}
