//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUGIAO
    {
        public int mathietbi { get; set; }
        public int maphieugiao { get; set; }
        public Nullable<int> soluong { get; set; }
        public int ID { get; set; }
    
        public virtual PHIEUGIAO PHIEUGIAO { get; set; }
        public virtual THIETBI THIETBI { get; set; }
    }
}
