//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONVI
    {
        public int madonvi { get; set; }
        public string tendonvi { get; set; }
        public string ghichu { get; set; }
        public Nullable<int> maphieugiao { get; set; }
    
        public virtual PHIEUGIAO PHIEUGIAO { get; set; }
    }
}
