//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUNHAP
    {
        public int maphieunhap { get; set; }
        public Nullable<System.DateTime> ngaynhap { get; set; }
        public Nullable<int> manhacungcap { get; set; }
        public Nullable<int> mathietbi { get; set; }
        public Nullable<int> soluong { get; set; }
    
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual THIETBI THIETBI { get; set; }
    }
}
